base_url = 'http://data.people.com.cn.proxy.library.georgetown.edu/rmrb/s?qs='
qs = {"cds": [{"fld": "dataTime.start", "cdr": "AND", "hlt": "false", "vlr": "AND", "qtp": "DEF", "val": "1993-01-01"},
              {"fld": "dataTime.end", "cdr": "AND", "hlt": "false", "vlr": "AND", "qtp": "DEF", "val": "2020-06-15"},
              {"cdr": "AND", "cds": [{"fld": "title", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马+枪支"},
                                     {"fld": "subTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马+枪支"},
                                     {"fld": "introTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马+枪支"},
                                     {"fld": "contentText", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马+枪支"}]},
              {"cdr": "AND", "cds": [{"fld": "title", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "subTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "introTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "contentText", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"}]},
              {"cdr": "AND", "cds": [{"fld": "title", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "subTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "introTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "contentText", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"}]},
              {"cdr": "AND", "cds": [{"fld": "title", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "subTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "introTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"},
                                     {"fld": "contentText", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马"}]},
              {"cdr": "AND", "cds": [{"fld": "title", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马+枪支+暴力"},
                                     {"fld": "subTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马+枪支+暴力"},
                                     {"fld": "introTitle", "cdr": "OR", "hlt": "true", "vlr": "OR", "val": "奥巴马+枪支+暴力"},
                                     {"fld": "contentText", "cdr": "OR", "hlt": "true", "vlr": "OR",
                                      "val": "奥巴马+枪支+暴力"}]}], "obs": [{"fld": "dataTime", "drt": "ASC"}]}
base_url_tail = '&tr=A&ss=1&pageNo=2&pageSize=50'
